// This is matches currency name to the country that uses that currency
// Ireland is used for Euros
// For some south asian countries the price is in usd but it's different to the United States price
const currencyList = {
  AED: { symbol: 'AED', countryCode: 'AE' },
  ARS: { symbol: 'AR$', countryCode: 'AR' },
  AUD: { symbol: 'AU$', countryCode: 'AU' },
  BRL: { symbol: 'R$', countryCode: 'BR' },
  CAD: { symbol: 'CA$', countryCode: 'CA' },
  CHF: { symbol: 'CHF', countryCode: 'CH' },
  CLP: { symbol: 'CL$', countryCode: 'CL' },
  CNY: { symbol: 'CN¥', countryCode: 'CN' },
  COP: { symbol: 'CO$', countryCode: 'CO' },
  CRC: { symbol: '₡', countryCode: 'CR' },
  EUR: { symbol: '€', countryCode: 'IE' },
  GBP: { symbol: '£', countryCode: 'GB' },
  HKD: { symbol: 'HK$', countryCode: 'HK' },
  ILS: { symbol: '₪', countryCode: 'IL' },
  IDR: { symbol: 'Rp', countryCode: 'ID' },
  INR: { symbol: 'Rs', countryCode: 'IN' },
  JPY: { symbol: '¥', countryCode: 'JP' },
  KRW: { symbol: '₩', countryCode: 'KR' },
  KWD: { symbol: 'KD', countryCode: 'KW' },
  KZT: { symbol: 'KZT', countryCode: 'KZ' },
  MXN: { symbol: 'MX$', countryCode: 'MX' },
  MYR: { symbol: 'RM', countryCode: 'MY' },
  NOK: { symbol: 'Nkr', countryCode: 'NO' },
  NZD: { symbol: 'NZ$', countryCode: 'NZ' },
  PEN: { symbol: 'S/.', countryCode: 'PE' },
  PHP: { symbol: '₱', countryCode: 'PH' },
  PLN: { symbol: 'zł', countryCode: 'PL' },
  QAR: { symbol: 'QR', countryCode: 'QA' },
  RUB: { symbol: 'RUB', countryCode: 'RU' },
  SAR: { symbol: 'SR', countryCode: 'SA' },
  SGD: { symbol: 'S$', countryCode: 'SG' },
  THB: { symbol: '฿', countryCode: 'TH' },
  TRY: { symbol: 'TL', countryCode: 'TR' },
  TWD: { symbol: 'NT$', countryCode: 'TW' },
  UAH: { symbol: '₴', countryCode: 'UA' },
  USD: { symbol: '$', countryCode: 'US' },
  UYU: { symbol: '$U', countryCode: 'UY' },
  VND: { symbol: '₫', countryCode: 'VN' },
  ZAR: { symbol: 'R', countryCode: 'ZA' }
}
